// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const newChirp = `-- name: NewChirp :one
insert into chirps (id, created_at, updated_at, body, author_id)
values (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2
)
returning id, created_at, updated_at, body, author_id
`

type NewChirpParams struct {
	Body     string
	AuthorID uuid.UUID
}

func (q *Queries) NewChirp(ctx context.Context, arg NewChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, newChirp, arg.Body, arg.AuthorID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.AuthorID,
	)
	return i, err
}
