// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: drop_users.sql

package database

import (
	"context"
)

const dropUsers = `-- name: DropUsers :exec
delete from users
`

func (q *Queries) DropUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, dropUsers)
	return err
}
