// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: get_single_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getSingleChirp = `-- name: GetSingleChirp :one
select id, created_at, updated_at, body, author_id from chirps
where id = $1
`

func (q *Queries) GetSingleChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getSingleChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.AuthorID,
	)
	return i, err
}
